apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: solar-controller-hpa
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: solar-controller
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageUtilization: 80
        type: Utilization
  behavior:
    scaleUp:
      policies:
      - type: Percent
        value: 50
        periodSeconds: 10
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30
