apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: node-network-loss-by-names
spec:
  experiments:
  - scope: node
    target: network
    action: loss
    desc: "node network loss"
    matchers:
    - name: names
      value: ["node"]
    - name: percent
      value: ["100"]
    - name: interface
      value: ["ens192"]
