apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  hub: registry.cn-shenzhen.aliyuncs.com/solarmesh
  tag: 1.11.5
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster1
      network: network1

