apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: demo
  namespace: istio-system
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
      proxyStatsMatcher:
        inclusionPrefixes:
          - solarmesh
      extraStatTags:
        - istio_version  
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster1
      network: network1
      tracer:
        zipkin:
          address: jaeger.jaeger-infra:9411
    telemetry:
      enabled: true
      v2:
        enabled: true
        prometheus:
          configOverride:
            inboundSidecar:
              definitions:
                - name: solarmesh_requests_total
                  type: "COUNTER"
                  value: "1"
              metrics:
                - name: solarmesh_requests_total
                  dimensions:
                    istio_version: downstream_peer.istio_version
            outboundSidecar:
              definitions:
                - name: solarmesh_requests_total
                  type: "COUNTER"
                  value: "1"
              metrics:
                - name: solarmesh_requests_total
                  dimensions:
                    istio_version: upstream_peer.istio_version
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway
      istio-egressgateway:
        injectionTemplate: gateway  
  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: true
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s: 
          service:
            ports:
              - name: promethues
                port: 9090
                protocol: TCP
                targetPort: 9090
              - name: kiali
                port: 20001
                protocol: TCP
                targetPort: 20001
              - name: networking-agent
                port: 7575
                protocol: TCP
                targetPort: 7575
              - name: bookinfo
                port: 9080
                protocol: TCP
                targetPort: 9080
              - name: grafana
                port: 3000
                protocol: TCP
                targetPort: 3000
              - name: jaeger
                port: 16686
                protocol: TCP
                targetPort: 16686
              - name: status-port
                port: 15021
                protocol: TCP
                targetPort: 15021
              - name: http2
                port: 80
                protocol: TCP
                targetPort: 8080
              - name: https
                port: 443
                protocol: TCP
                targetPort: 8443
              - name: tcp
                port: 31400
                protocol: TCP
                targetPort: 31400
              - name: tls
                port: 15443
                protocol: TCP
                targetPort: 15443
